#!/bin/bash

INIT_FILE=patch/init.sql;

printf "\n-- THIS FILE IS AUTOGENERATED. DO NOT EDIT.\n" >> $INIT_FILE

cat patch/base.sql > $INIT_FILE;

for schema in main core
do
  # shellcheck disable=SC2129
  printf "\n------------------------------------------------------------------------------------------------------------------------\n" >> $INIT_FILE

  cat database/$schema/$schema.sql >> $INIT_FILE

  printf "\n------------------------------------------------------------------------------------------------------------------------" >> $INIT_FILE
done;

# shellcheck disable=SC2231
for table in database/main/tables/*
do
  # shellcheck disable=SC2129
  printf "\n\n" >> $INIT_FILE
  cat "$table" >> $INIT_FILE
  printf "\n------------------------------------------------------------------------------------------------------------------------" >> $INIT_FILE
done
printf "\n------------------------------------------------------------------------------------------------------------------------" >> $INIT_FILE

# shellcheck disable=SC2231
for view in database/core/views/*
do
  # shellcheck disable=SC2129
  printf "\n\n" >> $INIT_FILE
  cat "$view" >> $INIT_FILE
  printf "\n------------------------------------------------------------------------------------------------------------------------" >> $INIT_FILE
done
printf "\n------------------------------------------------------------------------------------------------------------------------" >> $INIT_FILE

# shellcheck disable=SC2231
for function in database/core/functions/*
do
  # shellcheck disable=SC2129
  printf "\n------------------------------------------------------------------------------------------------------------------------" >> $INIT_FILE
  # shellcheck disable=SC2129
  printf "\n\n" >> $INIT_FILE
  # shellcheck disable=SC2086
  cat $function >> $INIT_FILE
  printf "\n------------------------------------------------------------------------------------------------------------------------" >> $INIT_FILE
done

printf "\n------------------------------------------------------------------------------------------------------------------------\n" >> $INIT_FILE